# Generated by Django 3.2.3 on 2021-06-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
