# Generated by Django 3.2.3 on 2021-06-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_article_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.CharField(max_length=50000),
        ),
    ]
